x=float(input("Enter value of X="))
y=float(input("Enter value of Y="))

print("Addition of x+y=",x+y)
print("Substraction of x-y=",x-y)
print("Multiplication of x*y=",x*y)
print("Division of x/y=",x/y)
print("Modulus of x%y=",x%y)
print("Exponentiation of x**y=",x**y)
print("Floor division of x//y=",x//y)